#ifndef CUDA_WRAP_RUN_CONTROL_H
#define CUDA_WRAP_RUN_CONTROL_H

#define CUDA_WRAP_CHECK_ALLOWED

#define CUDA_WRAP_VERIFICATION_ALLOWED

#define CUDA_WRAP_VERIFICATION00_ALLOWED

#define CUDA_WRAP_CHECK_BEAM_VALUES_ALLOWED

#define CUDA_WRAP_COMPARE_BEAM_CURRENTS_ALLOWED

#define COPY_BEAM_FROM_HOST

#define CUDA_WRAP_CHECK_HIDDEN_VALUES

#define CUDA_WRAP_PARTICLE_HOST_COMPUTATIONS

#define CUDA_WRAP_CHECK_FIELD

#define CUDA_WRAP_COMPUTE_BEAM_ON_HOST

#define CUDA_WRAP_FFTW_ALLOWED

#define CUDA_WRAP_POISSON_LOOPS_ALLOWED

//#define BATCH_FOURIER_TIME_PRINT

//#define 2D_FOURIER_TIME_PRINT

//#define TRANSPOSE_TIME_PRINT

//#define GUESS_TIME_PRINT

// #define CUDA_WRAP_PRINT_D_MATRIX

#define CUDA_WRAP_COPY_ALLOWED

#define CUDA_WRAP_HOST_COMPUTATIONS

#define CUDA_WRAP_FIELD_OUTPUT

#define CUDA_WRAP_CUPRINTF_IN_OUT

#define CUDA_WRAP_CUPRINTF_ALL

#define CUDA_WRAP_CHECK_LAYER

//#define CUDA_WRAP_CHECK_IN_OUT

//#define CUDA_WRAP_CHECK_ALL

//#define CUDA_WRAP_TIME_PRINT

//#define CUDA_WRAP_CONTROL

#define CUDA_WRAP_CHECK_PARTICLE_ATTRIBUTES 

#define CUDA_WRAP_CHECK_PARTICLE_VALUES

#define CUDA_WRAP_COMPARE_PARTICLE_TRACE_DETAILS

#define CUDA_WRAP_PARTICLE_CONTROL_FILE

#define CUDA_WRAP_SINGLE_PARTICLE_TRACE

#define CUDA_WRAP_SINGLE_PARTICLE_TRACE_NY 1

#define CUDA_WRAP_SINGLE_PARTICLE_TRACE_NZ 1

#define CUDA_WRAP_PARTICLE_DEVICE_CONTROL_FILE

#define CHECK_DETAILS DETAILS

#define CUDA_WRAP_CURRENTS_CHECK

#define CONTROL_FFT_LAYER 1000

#define CUDA_WRAP_PARTICLE_VALUES_DETAILS

#define CUDA_WRAP_BEAM_VALUES_DETAILS

#define BEAM_VALUES_NUMBER 170

#define PLASMA_VALUES_NUMBER 200

#define POSITION(i,n,num_attr)  ( (i)*(num_attr)   )

#define PLASMA_MOVE_CUPRINTF

#define PLASMA_VALUES_CUPRINTF

#define CUDA_WRAP_CHECK_PLASMA_VALUES_ALLOWED

#define BEAM_TOLERANCE 1e-14

#define CUDA_WRAP_TN 12

#define HALF_INT_TN  22

//#define CUDA_WRAP_EMERGENCY_HIDDEN

//#define CUDA_WRAP_EMERGENCY_MATRIX_COPY

#define LAYER_PARTICLE_PRINT_NUMBER 10

//#define CUDA_WRAP_PRINT_PLASMA_VALUES

//#define CUDA_WRAP_HIDDEN_CURRENTS_CHECK

//#define  CUDA_WRAP_TEST_TRANSVERSE_FIELD

//#define PARALLEL_ONLY

#define FLYING_PARTICLES_RATIO 0.01

//#define CUDA_WRAP_PRINT_BEAM_10_PARTICLES

#define CUDA_WRAP_PRINT_10_PARTICLES

#define BEAM_DEFAULT_NUMBER  1000000

// #define CUDA_WRAP_PRINT_CENTRE

//#define VERIFY_ALL_VECTORS

#define CUDA_WRAP_DEBUG_ERROR_MESSAGES

#define CPU_COMPUTING

//#define CUDA_WRAP_PARALLEL_DEBUG

//#define CUDA_WRAP_LOOP_PARALLEL_DEBUG

//#define CUDA_WRAP_HIGH_PARALLEL_DEBUG 

#define CUDA_WRAP_BEAM_3D_DENSITY_PRINT

#define CUDA_WRAP_BEAM_PARTICLES_PRINT

#endif
