#ifndef CUDA_WRAP_EMERGENCY_H
#define CUDA_WRAP_EMERGENCY_H

void CUDA_WRAP_EMERGENCY_COPY_LONGITUDINAL_CURRENTS(int ny,int nz);
void CUDA_WRAP_EMERGENCY_COPY_TRANSVERSE_CURRENTS(int ny,int nz);

#endif